baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Personal Website'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'archetypes'
target = 'archetypes'

[[module.mounts]]
source = 'data'
target = 'data'

[[module.mounts]]
source = 'i18n'
target = 'i18n'

[[module.mounts]]
source = 'layouts'
target = 'layouts'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
